main:
  delay: 10
  repeat_period: 30

telegram:
  token: 
  group: 
  proxy:
  
http:
  repeat: 5
  timeout: 10
  sites:

icmp:
  timeout: 4
  timedelay: 100

  hosts:
    - 192.168.1.2
    - 192.168.1.4
    - 192.168.1.5
    - 192.168.1.6
    - 192.168.1.7
    - 192.168.1.8
